---
- name: "create project dir"
  file:
    path: "{{ dest }}"
    state: directory
    owner: root
    group: root
    mode: 2400
- name: "supply docker-compose"
  template:
    src: "{{ config }}/docker-compose.j2"
    dest: "{{ dest }}/docker-compose.yml"
    mode: 0500
- name: "supply app envs"
  copy:
    src: "/secret/api/envs/{{ config }}"
    dest: "{{ dest }}.env"
    mode: 0400
